name: buyandbye
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  firebase_auth_web:
  firebase_analytics:
  cloud_firestore_web:
  flutter_spinkit:
  cloud_firestore:
  firebase_storage:
  google_sign_in:
  provider:
  firebase_core:
  curved_navigation_bar:
  get_it:
  shared_preferences:
  random_string:
  cached_network_image:
  line_icons:
  carousel_slider:
  animate_do:
  flutter_svg:
  flutter_launcher_icons:
  firebase_messaging: 
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  theme_provider:
  get:
  google_maps_flutter:
  apple_sign_in:
  sign_in_with_apple:
  flutter_local_notifications:
  geolocator:
  clippy_flutter:
  flutter_restart:
  geoflutterfire:
  rxdart:
  slide_popup_dialog:
  ndialog:
  google_nav_bar:
  flutter_statusbarcolor:
  location: 
  progress_dialog:
  cupertino_icons: ^1.0.0 
  flutter_credit_card:
  flutter_app_badger:
  animations:
  image_picker: 
  image_cropper:  
  photo_view: 
  font_awesome_flutter:
  url_launcher:
  intl:
  shimmer:
  geocoder:
  firebase_storage_web:
  status_alert:
  flutter_add_to_cart_button:
  #flutter_stripe:
  http:
  stripe_payment:
  truncate:
  flutter_native_splash:
  flutter_launcher_name:
  wave: ^0.2.0






  
flutter_native_splash:
  #color: "#42a5f5"
  background_image: assets/images/splash.png
  image: assets/logo/logo.png
  android: true
  ios: true
  #android_gravity: fill
  ios_content_mode: scaleAspectFit

flutter_launcher_name:
  name: "Buy & Bye"



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/
    - assets/images/avatar.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
